name: frienderr
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  video_compress: ^3.1.0
  visibility_detector: ^0.2.2
  

dev_dependencies:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  path: ^1.8.0
  meta: ^1.3.0
  
  injectable_generator: ^1.5.3
  
  get_it: ^7.2.0
  dartz: ^0.10.1
  cool_dropdown: ^1.4.1
  bitmap: ^0.1.0
  flutter_sound: ^9.2.13
  blurrycontainer: ^0.1.0
  shimmer: ^2.0.0
  graphql_flutter: ^5.1.0
  auto_size_text: ^3.0.0
  auto_route: ^3.2.4
  equatable: ^2.0.3 
  injectable: ^1.5.3
  jaguar_jwt: ^3.0.0
  flutter_svg: ^1.0.3
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.0.0
  firebase_auth: ^3.3.9

  firebase_core: ^1.13.1
  path_provider: ^2.0.2
  blur_bottom_bar: ^1.0.3
  flutter_staggered_animations: ^1.0.0

  share: ^2.0.4
  camera: ^0.9.4+16
  like_button: ^2.0.2
  
  rive: ^0.8.4
  flutter_spinkit: ^5.1.0
  file_picker: ^4.5.1
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.2
  connectivity_plus: ^2.2.0
  json_serializable: ^6.1.5
  sliding_up_panel: ^2.0.0+1
  shared_preferences: ^2.0.6
  firebase_analytics: ^9.1.2
  firebase_messaging: ^11.2.8
  auto_route_generator: ^3.2.3
  curved_navigation_bar: ^1.0.1
  animated_splash_screen: ^1.1.0
  firebase_dynamic_links: ^4.0.8
  flutter_launcher_icons: ^0.9.0
  provider: ^6.0.2
  cube_transition_plus: ^2.0.1
  persistent_bottom_nav_bar: ^4.0.2
  material_design_icons_flutter: ^5.0.6595
  badges: ^2.0.2
  story_view: ^0.13.1
  fluttericon: ^2.0.0
  flutter_local_notifications: ^9.5.3+1
  image_picker: ^0.8.4+10
  google_maps_flutter: ^2.1.4
  photo_manager: ^2.1.1
  video_player: ^2.3.0
  time_elapsed: ^0.2.4+2
  dots_indicator: ^2.0.0
  carousel_slider: ^4.0.0
  flutter_slidable: ^1.2.0
  firebase_storage: ^10.2.9
  permission_handler: ^8.2.5
  inview_notifier_list: ^3.0.0
  cached_network_image: ^3.1.0

  bloc: ^8.0.3
  just_audio: ^0.9.24
  flutter_dotenv: ^5.0.2
  freezed: ^1.1.1
  siri_wave: ^0.2.1
  location: ^4.4.0 
  flutter_stories: ^0.3.1
  audio_session: ^0.1.7
  flutter_audio_waveforms: ^1.2.1+6
  learning_smart_reply: ^0.0.2
  google_mlkit_smart_reply: ^0.3.0
  animations: ^2.0.1
  dash_chat_2:
    git:
      url: https://github.com/droperr/dash_chat_2.1/
      ref: main # branch name
  geolocator: ^8.0.5 
  build_runner: ^2.0.4
  media_gallery: ^0.1.5
  flare_flutter: ^3.0.2
  bottom_navy_bar: ^6.0.0
  pull_to_refresh: ^2.0.0
  json_annotation: ^4.5.0
  freezed_annotation: ^1.1.0
  flutter_cache_manager: ^3.1.2
  
  flutter_staggered_grid_view: ^0.6.1
  
flutter_test:
    sdk: flutter


flutter_icons:
  ios: true
  android: true
  adaptive_icon_background: "#000000"
  image_path: "assets/images/appicon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/map_styles/
    - assets/animations/
    - assets/deep_ar/

  fonts:
    - family: Inter
      fonts:
         - asset: assets/fonts/Inter-Medium.ttf
    - family: Montserrat
      fonts:
         - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Roboto
      fonts:
         - asset: assets/fonts/Roboto-Regular.ttf
    - family: OpenSans
      fonts:
         - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
    - family: Raleway
      fonts:
         - asset: assets/fonts/Raleway-Regular.ttf


        