name: frienderr
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  path: ^1.8.0
  meta: ^1.3.0
  shimmer: ^2.0.0
  equatable: ^2.0.3 
  jaguar_jwt: ^3.0.0
  flutter_bloc: ^7.0.1
  json_annotation: any
  hydrated_bloc: ^7.0.1
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  path_provider: ^2.0.2
  flutter_staggered_animations: ^1.0.0
  
  cloud_firestore: ^2.2.2
  cupertino_icons: ^1.0.2
  sliding_up_panel: ^2.0.0+1
  connectivity_plus: ^1.0.4
  json_serializable: ^4.1.3
  responsive_flutter: ^0.0.4
  shared_preferences: ^2.0.6
  firebase_analytics: ^5.0.2
  firebase_messaging: ^10.0.4
  curved_navigation_bar: ^1.0.1
  animated_splash_screen: ^1.1.0
  firebase_dynamic_links: ^2.0.7
  flutter_launcher_icons: ^0.9.0
  flutter_page_transition: ^0.1.0
  persistent_bottom_nav_bar: ^4.0.2
  material_design_icons_flutter: ^4.0.5955
  share: ^2.0.4
  camera: ^0.8.1+5
  like_button: ^2.0.2
  story_view: ^0.13.1
  fluttericon: ^2.0.0
  image_picker: ^0.7.4
  photo_manager: ^1.2.5
  video_player: ^2.1.10
  time_elapsed: ^0.2.4+2
  dots_indicator: ^2.0.0
  carousel_slider: ^4.0.0
  flutter_slidable: ^0.6.0
  firebase_storage: ^10.0.1
  permission_handler: ^7.0.0
  inview_notifier_list: ^2.0.0
  cached_network_image: ^3.1.0
  flutter_image_compress: ^1.0.0
 

  bloc: ^7.0.0
  geocoder: ^0.2.1
  provider: ^5.0.0
  location: ^4.2.0 
  thumbnails: ^1.0.1
  animations: ^2.0.1
  dash_chat: ^1.1.16
  build_runner: ^2.0.4
  geolocator: ^7.2.0+1
  media_gallery: ^0.1.5
  bottom_navy_bar: ^6.0.0
  pull_to_refresh: ^2.0.0
  google_maps_flutter: ^2.0.6
  flutter_cache_manager: ^3.1.2
  flutter_staggered_grid_view: ^0.4.0
  
flutter_test:
    sdk: flutter


flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/appicon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/map_styles/

  fonts:
    - family: Inter
      fonts:
         - asset: fonts/Inter-Medium.ttf
    - family: Montserrat
      fonts:
         - asset: fonts/Montserrat-Regular.ttf
